### ISSUE TITLE
Double-press to select all voices not working

### ISSUE THREAD

**Issue by pfig** [synthetiv/fretwork#5]
When trying to select all voices by double-pressing one of the 4 voice selectors on the left-most column, only the voice corresponding to the key pressed is selected.

**Comment by synthetiv** [comment]
How quickly are you double-pressing the voice button? I should make this clearer in the documentation, but the second press has to happen within 0.2 seconds of the first -- it should be like double-clicking a mouse, not just clicking twice. (If that's not working, then something else is wrong...)

**Comment by pfig** [comment]
Got it to work now (by double-tapping faster :) but still not 100% of the time - I can't see a pattern, so I'll just put it down to being slow sometimes.
