### ISSUE TITLE
Static modes on the gate roll page all behave in the same way

### ISSUE THREAD

**Issue by pfig** [synthetiv/fretwork#6]
Maybe I'm not understanding this correctly:

> press (14, 1) to activate static mode and move left, and (16, 1) to activate static mode and move right.

I can't see any difference between the three.

**Comment by synthetiv** [comment]
Strange -- I'll make a video of the way it should behave later tonight.

**Comment by synthetiv** [comment]
Just realized this may just be something I need to clarify in the docs -- the left + right keys are really for scrolling while you're in static mode. They don't activate a different "static and move left/right" mode, they just happen to enter static mode when you first press them, if it isn't active already.

Repeatedly pressing the left or right key should shift the lit LEDs left or right.

**Comment by synthetiv** [comment]
@pfig does this look like how it's behaving for you?

https://vimeo.com/421139657

**Comment by pfig** [comment]
Yep!
